In [1]:
import tensorflow as tf

In [2]:
#n_inputs = 3
#n_neurons= 5

#X0 = tf.placeholder(tf.float32, [None, n_inputs])
#X1 = tf.placeholder(tf.float32, [None, n_inputs])

#basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
#output_seqs, states = tf.contrib.rnn.static_rnn(basic_cell, [X0, X1], dtype=tf.float32)

#Y0, Y1 = output_seqs

In [4]:
n_inputs = 3
n_neurons= 5
n_steps = 2
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
X_seqs = tf.unstack(tf.transpose(X, perm=[1, 0, 2])) # X_seqs = [X_0, X_1, X_2 ... X_n] for n-steps

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
output_seqs, states = tf.contrib.rnn.static_rnn(basic_cell, X_seqs, dtype=tf.float32)

outputs = tf.transpose(tf.stack(output_seqs), perm=[1,0,2])

Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.


In [5]:
init = tf.global_variables_initializer()

In [6]:
import numpy as np

# Mini-batch
X_batch = np.array([ 
    [[0, 1, 2], [9, 8, 7]],
    [[3, 4, 5], [0, 0, 0]],
    [[6, 7, 8], [6, 5, 4]],
    [[9, 0, 1], [3, 2, 1]]])

with tf.Session() as sess:
    init.run()
    outputs_val = outputs.eval(feed_dict={X: X_batch})

In [8]:
print(outputs_val)

[[[-0.254056   -0.618339   -0.37141547  0.7546131   0.1335104 ]
  [ 0.99926084 -0.9999862  -0.9999989  -0.08789495 -0.9569771 ]]

 [[ 0.770983   -0.9972153  -0.99394166  0.83302087 -0.35803068]
  [ 0.79322326  0.87146944  0.11817493 -0.42538187  0.15635826]]

 [[ 0.98030174 -0.99998355 -0.9999597   0.8879747  -0.7081997 ]
  [ 0.9995793  -0.9959626  -0.99962133 -0.8436101  -0.6766966 ]]

 [[ 0.9324256  -0.99998474 -0.9994141  -0.98102224 -0.99992424]
  [ 0.99892396 -0.9469086  -0.9864506  -0.9755598   0.17285477]]]
